# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Source/Furnace/cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Source/Furnace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Source/Furnace/CMakeFiles /home/pi/Source/Furnace/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Source/Furnace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FurnaceXX

# Build rule for target.
FurnaceXX: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FurnaceXX
.PHONY : FurnaceXX

# fast build rule for target.
FurnaceXX/fast:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/build
.PHONY : FurnaceXX/fast

Enemy.o: Enemy.cpp.o

.PHONY : Enemy.o

# target to build an object file
Enemy.cpp.o:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/Enemy.cpp.o
.PHONY : Enemy.cpp.o

Enemy.i: Enemy.cpp.i

.PHONY : Enemy.i

# target to preprocess a source file
Enemy.cpp.i:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/Enemy.cpp.i
.PHONY : Enemy.cpp.i

Enemy.s: Enemy.cpp.s

.PHONY : Enemy.s

# target to generate assembly for a file
Enemy.cpp.s:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/Enemy.cpp.s
.PHONY : Enemy.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/Game.cpp.s
.PHONY : Game.cpp.s

GameObject.o: GameObject.cpp.o

.PHONY : GameObject.o

# target to build an object file
GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/GameObject.cpp.o
.PHONY : GameObject.cpp.o

GameObject.i: GameObject.cpp.i

.PHONY : GameObject.i

# target to preprocess a source file
GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/GameObject.cpp.i
.PHONY : GameObject.cpp.i

GameObject.s: GameObject.cpp.s

.PHONY : GameObject.s

# target to generate assembly for a file
GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/GameObject.cpp.s
.PHONY : GameObject.cpp.s

GameStateMachine.o: GameStateMachine.cpp.o

.PHONY : GameStateMachine.o

# target to build an object file
GameStateMachine.cpp.o:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/GameStateMachine.cpp.o
.PHONY : GameStateMachine.cpp.o

GameStateMachine.i: GameStateMachine.cpp.i

.PHONY : GameStateMachine.i

# target to preprocess a source file
GameStateMachine.cpp.i:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/GameStateMachine.cpp.i
.PHONY : GameStateMachine.cpp.i

GameStateMachine.s: GameStateMachine.cpp.s

.PHONY : GameStateMachine.s

# target to generate assembly for a file
GameStateMachine.cpp.s:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/GameStateMachine.cpp.s
.PHONY : GameStateMachine.cpp.s

InputHandler.o: InputHandler.cpp.o

.PHONY : InputHandler.o

# target to build an object file
InputHandler.cpp.o:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/InputHandler.cpp.o
.PHONY : InputHandler.cpp.o

InputHandler.i: InputHandler.cpp.i

.PHONY : InputHandler.i

# target to preprocess a source file
InputHandler.cpp.i:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/InputHandler.cpp.i
.PHONY : InputHandler.cpp.i

InputHandler.s: InputHandler.cpp.s

.PHONY : InputHandler.s

# target to generate assembly for a file
InputHandler.cpp.s:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/InputHandler.cpp.s
.PHONY : InputHandler.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/Player.cpp.s
.PHONY : Player.cpp.s

TextureManager.o: TextureManager.cpp.o

.PHONY : TextureManager.o

# target to build an object file
TextureManager.cpp.o:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/TextureManager.cpp.o
.PHONY : TextureManager.cpp.o

TextureManager.i: TextureManager.cpp.i

.PHONY : TextureManager.i

# target to preprocess a source file
TextureManager.cpp.i:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/TextureManager.cpp.i
.PHONY : TextureManager.cpp.i

TextureManager.s: TextureManager.cpp.s

.PHONY : TextureManager.s

# target to generate assembly for a file
TextureManager.cpp.s:
	$(MAKE) -f CMakeFiles/FurnaceXX.dir/build.make CMakeFiles/FurnaceXX.dir/TextureManager.cpp.s
.PHONY : TextureManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... FurnaceXX"
	@echo "... edit_cache"
	@echo "... Enemy.o"
	@echo "... Enemy.i"
	@echo "... Enemy.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... GameObject.o"
	@echo "... GameObject.i"
	@echo "... GameObject.s"
	@echo "... GameStateMachine.o"
	@echo "... GameStateMachine.i"
	@echo "... GameStateMachine.s"
	@echo "... InputHandler.o"
	@echo "... InputHandler.i"
	@echo "... InputHandler.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... TextureManager.o"
	@echo "... TextureManager.i"
	@echo "... TextureManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

